namespace ArbiScan.Core.Models;

public sealed record HealthReport(
    SummaryPeriod Period,
    DateTimeOffset GeneratedAtUtc,
    DateTimeOffset FromUtc,
    DateTimeOffset ToUtc,
    string Symbol,
    long HealthyDurationMs,
    long DegradedDurationMs,
    IReadOnlyDictionary<string, int> ReconnectCountByExchange,
    IReadOnlyDictionary<string, int> ResyncCountByExchange,
    IReadOnlyDictionary<string, int> StaleCountByExchange,
    IReadOnlyDictionary<string, int> StaleDetectedCountByExchange,
    IReadOnlyDictionary<string, int> StaleRecoveredCountByExchange,
    IReadOnlyDictionary<string, int> StaleFlapCountByExchange,
    IReadOnlyDictionary<string, int> TopDegradationCauses,
    IReadOnlyDictionary<string, long> LongestStaleIntervalMsByExchange,
    IReadOnlyDictionary<string, double> AverageStaleDurationMsByExchange,
    IReadOnlyDictionary<string, double> MedianStaleDurationMsByExchange,
    IReadOnlyDictionary<string, double> MaxStaleDurationMsByExchange,
    IReadOnlyDictionary<string, double> P95StaleDurationMsByExchange,
    IReadOnlyDictionary<string, double> AverageDataAgeMsByExchange,
    IReadOnlyDictionary<string, double> P95DataAgeMsByExchange,
    IReadOnlyDictionary<string, double> MaxDataAgeMsByExchange,
    IReadOnlyDictionary<string, double> AverageCallbackSilenceMsByExchange,
    IReadOnlyDictionary<string, double> P95CallbackSilenceMsByExchange,
    IReadOnlyDictionary<string, double> MaxCallbackSilenceMsByExchange,
    IReadOnlyDictionary<string, string> StaleLikelyRootCauseByExchange,
    IReadOnlyDictionary<string, DateTimeOffset?> LastStaleDetectedAtUtcByExchange,
    IReadOnlyDictionary<string, DateTimeOffset?> LastReconnectAtUtcByExchange,
    IReadOnlyDictionary<string, DateTimeOffset?> LastResyncAtUtcByExchange);
