using ArbiScan.Core.Enums;

namespace ArbiScan.Core.Models;

public sealed record StaleDiagnosticEvent(
    DateTimeOffset TimestampUtc,
    ExchangeId Exchange,
    string EventType,
    string Symbol,
    int QuoteStalenessThresholdMs,
    int QuoteStalenessConfirmationMs,
    int ScanIntervalMs,
    OrderBookSyncStatus OrderBookStatus,
    DateTimeOffset CapturedAtUtc,
    DateTimeOffset? UpdateTimeUtc,
    DateTimeOffset? UpdateServerTimeUtc,
    DateTimeOffset? LastSuccessfulCallbackUtc,
    double DataAgeMs,
    double DataAgeByExchangeTimestampMs,
    double CallbackSilenceMs,
    double DataAgeByLocalCallbackTimestampMs,
    double TimeSinceTopOfBookChangedMs,
    decimal? TopBid,
    decimal? TopAsk,
    int BidLevelsCount,
    int AskLevelsCount,
    decimal? BestBidQty,
    decimal? BestAskQty,
    DateTimeOffset LoopStartedAtUtc,
    DateTimeOffset LoopFinishedAtUtc,
    double LoopDurationMs,
    int ManagedThreadId,
    bool IsSnapshotUsableForEvaluation,
    IReadOnlyList<string> DegradedFlags,
    string StaleLikelyRootCause);
