namespace ArbiScan.Core.Models;

public sealed record SummaryReport(
    SummaryPeriod Period,
    DateTimeOffset GeneratedAtUtc,
    DateTimeOffset FromUtc,
    DateTimeOffset ToUtc,
    string Symbol,
    int RawObservationCount,
    int RawPositiveSignalCount,
    int FeePositiveSignalCount,
    int NetPositiveSignalCount,
    int EntryQualifiedSignalCount,
    int TotalWindows,
    IReadOnlyDictionary<string, int> WindowsByDirection,
    IReadOnlyDictionary<string, int> WindowsByNotional,
    double AverageLifetimeMs,
    double MedianLifetimeMs,
    long MaxLifetimeMs,
    decimal MaxGrossEdgeUsd,
    decimal MaxNetEdgeUsd,
    decimal AverageNetEdgeUsd,
    decimal TheoreticalNetPnlUsd,
    SummaryDebugStats DebugStats,
    string FinalAssessment);
