namespace ArbiScan.Core.Models;

public sealed record SummaryReport(
    SummaryPeriod Period,
    DateTimeOffset GeneratedAtUtc,
    DateTimeOffset FromUtc,
    DateTimeOffset ToUtc,
    string Symbol,
    int TotalWindows,
    IReadOnlyDictionary<string, int> WindowsByDirection,
    IReadOnlyDictionary<string, int> WindowsByNotional,
    int PositiveGrossWindows,
    int PositiveNetWindows,
    int AboveThresholdWindows,
    double AverageLifetimeMs,
    double MedianLifetimeMs,
    long MaxLifetimeMs,
    IReadOnlyDictionary<string, int> LifetimeDistribution,
    decimal TotalGrossPnlUsd,
    decimal TotalNetPnlUsd,
    decimal AverageNetPnlUsd,
    decimal MedianNetPnlUsd,
    decimal MaxNetPnlUsd,
    decimal MinNetPnlUsd,
    IReadOnlyDictionary<string, int> NetPnlDistribution,
    decimal TotalFeesUsd,
    decimal TotalBuffersUsd,
    decimal AverageNetRoiPct,
    int FillableCount,
    int PartiallyFillableCount,
    int NotFillableCount,
    decimal AverageFillableSize,
    decimal MinFillableSize,
    decimal MaxFillableSize,
    int ReconnectCount,
    int ResyncCount,
    int StaleIntervalCount,
    long HealthyDurationMs,
    long DegradedDurationMs,
    SummaryDebugStats DebugStats,
    string FinalAssessment);
